AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics:
  Enabled: false
